version: '3'

networks:
  logger_net:
        ipam:
            driver: default
            config:
                - subnet: 165.28.0.0/16
services:
  client:
    entrypoint: /bin/bash
    build: 
        context: .
        dockerfile: docker/alpine/Dockerfile.client
    container_name: client    
    env_file: 
       - docker/alpine/log.env
    command: -c "./build.sh alpine && ./test_client.exe ${server_ip}"
    networks:
      logger_net:
         ipv4_address: 165.28.1.1
    env_file: 
       - docker/alpine/log.env
    depends_on:
      - server