version: '3.7'

networks:
  logger_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16

services:
  alpine:    
    build: 
        context: .
        dockerfile: docker/alpine/Dockerfile
    container_name: alpine
    networks:
      logger_net:
         ipv4_address: 172.28.1.1
    volumes:
      - .:/app
    ports:
      - "8050:8050"
    privileged: true
    user: root