version: '3.3'

networks:
  logger_net:
        ipam:
            driver: default
            config:
                - subnet: 175.28.0.0/16
services:
  client:
    entrypoint: /bin/bash
    build: 
        context: ../../
        dockerfile: docker/ubuntu/Dockerfile-compose
    container_name: client      
    volumes:
      - ../../:/app
    command: -c "./build.sh ubuntu && ./test_client.exe ${ubuntu_server}"
    networks:
      logger_net:
         ipv4_address: 175.28.1.1
    depends_on:
      - server