apiVersion: apps/v1
kind: Deployment
metadata:
 name: logger-client
spec:
  selector:
    matchLabels:
      app: logger-client
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata: 
      labels:
        app: logger-client
    spec:
      containers:
      - name: client
        image: localhost:5000/logger_ubuntu:latest
        ports:
        - containerPort: 8050