apiVersion: v1
kind: Pod
metadata:
 name: logger-client
 labels:
    zone: prod
    version: v1
spec:
	  containers:
	  - name: client
	    image: alpine
          imagePullPolicy: Never
	    ports:
    - containerPort: 8081