apiVersion: v1
kind: Pod
metadata:
 name: logger-server
 labels:
    zone: prod
    version: v1
spec:
	  containers:
	  - name: server
	    image: alpine
          imagePullPolicy: Never
	    ports:
        - containerPort: 8081