apiVersion: v1
kind: Pod
metadata:
 name: logger-server
 labels:
    app: server
spec:
	  containers:
      - name: server
        image: localhost:5000/logger_alpine:latest
        ports:
          - containerPort: 8050