apiVersion: v1
kind: Pod
metadata:
 name: logger-server
 labels:
    app: server
spec:
	  containers:
      - name: server
        image: alpine
            imagePullPolicy: Never
        ports:
          - containerPort: 8081