version: '3.3'

networks:
  logger_net:
        ipam:
            driver: default
            config:
                - subnet: 165.28.0.0/16
services:
  server:
    entrypoint: /bin/bash
    build: 
        context: ../../
        dockerfile: Dockerfile-compose
    container_name: server
    volumes:
      - ../../:/app
    command: -c "./build.sh alpine && ./server.exe"  
    networks:
      logger_net:
          ipv4_address: "${alpine_server}"
    ports:
      - "8050:8050"

 