pipeline {
    agent { dockerfile true}
    environment {
        DOCKER_USER = credentials('docker-username')
        DOCKER_PASS = credentials('docker-password')
    }
    stages {
        stage('Build') {
            steps {
                sh '''
                ./build.sh
                '''
            }
        }
        stage('Test') {
            steps {
                sh '''
                ls
                '''
            }
        }
     }
}
