pipeline {
    agent { 
            dockerfile {
                filename 'Dockerfile'
                dir "${DOCK_PATH}"
            }
    }
    environment {
        DOCKER_USER = credentials('docker-username')
        DOCKER_PASS = credentials('docker-password')
    }
    stages {
        stage('Build') {
            steps {
                sh '''
                chmod +x build.sh
                ./build.sh
                '''
            }
        }
         stage('Smoke Test') {
            steps {
                ansiColor('vga') {
                    sh '''
                    chmod +x test/smoke/smoke.sh
                    test/smoke/smoke.sh 
                    '''
                }                
            }
        }
        stage('Functional Test') {
            steps {
                ansiColor('vga') {
                    sh '''
                    chmod +x test/functional/functional.sh
                    test/functional/functional.sh input/results.txt
                     '''

                }                
            }
        }
        stage('Acceptance Test') {
            steps {
                ansiColor('vga') {
                sh '''
                ls
                chmod +x test/acceptance/acceptance.sh
                test/acceptance/acceptance.sh input/results.txt
                
                '''
                }
            }
        }
     }
}
