pipeline {
    agent { dockerfile true
        reuse true}
    environment {
        DOCKER_USER = credentials('docker-username')
        DOCKER_PASS = credentials('docker-password')
    }
    stages {
        stage('Build') {
            steps {
                sh '''
                make -C src
                ./build.sh > output.out
                '''
            }
        }
        stage('Test') {
            steps {
                sh '''
                test/functional/functional.sh
                '''
            }
        }
     }
}
