on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - 'kelly-13-create-k8s-pods'
permissions: read-all

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps: 
      - name: checkout
        uses: actions/checkout@v2

      - name: Run the make build
        uses: ./
        run: |
          make -C src
