on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - 'kelly-13-create-k8s-pods'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps: 
      - name: Run the make build
        run: make -C src

